### ISSUE TITLE
Create the Sharpe Ratio Error Estimator

### ISSUE THREAD

**Issue by moneygeek** [enjine-com/mcos#10]
Make it a child of the `ErrorEstimator` class.

Mentioned in section 4.5 (iii) in the paper. See https://towardsdatascience.com/calculating-sharpe-ratio-with-python-755dcb346805 as an example implementation of the Sharpe ratio calculation.

**Comment by ochrist2** [comment]
@moneygeek in section 4.5 (iii) of the paper there's an equation for the the mean difference in Sharpe ratio, it's the mean difference in expected outcomes divided by the square root of the
mean difference in variance. Is this how we want to calculate the mean difference in Sharpe ratio, or is there something specific in the article you linked that's missing from the paper?

**Comment by moneygeek** [comment]
Yes, we want 4.5 (iii)
