### ISSUE TITLE
Implement style git hooks

### ISSUE THREAD

**Issue by moneygeek** [enjine-com/mcos#11]

**Comment by andystanley** [comment]
Just as a reference, https://pre-commit.com/ is a really solid library that has support for many popular hooks (flake8, autopep8, mypy, pylint).

**Comment by andystanley** [comment]
Also, the default line length of 79 characters set by pylint, flake8, autopep8 etc is a bit aggressive. PyCharm has a limit of 120 characters which may be more ideal.

**Comment by biskit1** [comment]
Thanks! Appreciate the help getting started :)
