### ISSUE TITLE
Create Hierarchical Risk Parity Optimizer

### ISSUE THREAD

**Issue by moneygeek** [enjine-com/mcos#5]
Make it a child of the `Optimizer` class.

**Comment by biskit1** [comment]
for personal reference: 
https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimisers.html#hierarchical-risk-parity-hrp

**Comment by moneygeek** [comment]
Thanks, let's test that package by comparing the results with that from our code. If the results are the same, let's use the PyPortfolioOpt
